---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: monitoring
  #namespace: flux-system
spec:
  interval: 10m0s
  ref:
    branch: main
  url: https://github.com/yashrathod915/CinemaGoApplication

