apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: flux-system
  labels:
    app: grafana
spec:
  type : NodePort
  #type: ClusterIP
  ports:
    - port: 30100
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: grafana
